[tools]
bat = "latest"
bun = "latest"
delta = "latest"
difftastic = "latest"
dust = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
node = "22.9.0"
rg = "latest"
ruby = "latest"
yq = "latest"
zoxide = "latest"
