[tools]
bat = "latest"
bitwarden = "latest"
bun = "latest"
delta = "latest"
difftastic = "latest"
dust = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
node = "22.9.0"
"github:bitwarden/sdk" = { version = "latest", version_prefix = "bws-v" }
jq = "latest"
rg = "latest"
ruby = "latest"
yq = "latest"
zoxide = "latest"
