[tools]
aws-cli = "latest"
bat = "latest"
delta = "latest"
difftastic = "latest"
dust = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
github-cli = "latest"
go = "1.24.5"
jq = "latest"
mold = "latest"
node = "latest"
python = "latest"
rg = "latest"
ruby = "latest"
rust = "latest"
task = "latest"
tmux = "latest"
uv = "latest"
wasmer = "latest"
wasmtime = "latest"
yq = "latest"
zellij = "latest"
zig = "latest"
zoxide = "latest"
